#pragma once

// From glfw3.h

#define HELL_MOUSE_BUTTON_1         0
#define HELL_MOUSE_BUTTON_2         1
#define HELL_MOUSE_BUTTON_3         2
#define HELL_MOUSE_BUTTON_4         3
#define HELL_MOUSE_BUTTON_5         4
#define HELL_MOUSE_BUTTON_6         5
#define HELL_MOUSE_BUTTON_7         6
#define HELL_MOUSE_BUTTON_8         7
#define HELL_MOUSE_BUTTON_LAST      HELL_MOUSE_BUTTON_8
#define HELL_MOUSE_BUTTON_LEFT      HELL_MOUSE_BUTTON_1
#define HELL_MOUSE_BUTTON_RIGHT     HELL_MOUSE_BUTTON_2
#define HELL_MOUSE_BUTTON_MIDDLE    HELL_MOUSE_BUTTON_3